clc
clear 
global G
global T
global Ns
global Np

%% 1: Standered_condtions & one-PV-module

Standered_condtions; % To find the paramters at the standered conditions (G=1000, T=25) where T is the cell temperature
%% 2: Maximum power generated by one PV module at different operating conditions
% Note: Do not run this one before the script (Standered_condtions)

G=800;
T=25;
[Pmax_one_module,Vmax_one_module]=PV_Maxim_power_one_module(G,T) 

%% 3: Maximum power generated by  PV Array at different operating conditions (Searching Method)
% Note: Do not run this one before the script (Standered_condtions)

G=800;
T=40;
Ns=3; % Number of PV modules connected in series in an array
Np=2; % Number of PV modules  connected in parallel in an array
Array
%% 4: Maximum power generated by  PV Array at different operating conditions (See Section: PV Array Configuration, Sizing Paper)
% Note: Do not run this one before the script (Standered_condtions)

G=800;
T=40;
Ns=3; % Number of PV modules connected in series in an array
Np=2; % Number of PV modules  connected in parallel in an array
Npv=Ns*Np; % Total PV modules
[Pmax_one_module,Vmax_one_module]=PV_Maxim_power_one_module(G,T); 
Pmax=Pmax_one_module*Npv % Maximum power generated by  PV Array
Vmax=Vmax_one_module*Ns  % Voltage at the Maximum power point
