% This function calculate the maximum power of (one) PV module at different operating conditions (G,T)
% The maximum power generated by Array  linearly depends  on the total PV modules, see Section: PV Array Configuration in the sizing paper

function [Pmax,Vmax] =PV_Maximum_Power_One_Module(G,T)
global Im
global Vm
global Isc_n
global  Voc_n
global Kv
global  Ki
global Nc_m_s
global  Nc_m_p
global  Gn
global T_ref
global n
global detla
global k
global q
global Vt
global  a
global Rshn
global Rs
global Ipvn
% global Ion

%% Manufacturer Datasheet
Nc_m_s=54; % Number of cells connected in series in one module
Nc_m_p=1; % Number of cells connected in parallel in one module
Im=7.61;
Vm=26.3;
Isc_n=8.21;
Voc_n=32.9;
Kv=-0.123;
Ki=0.0032;
Gn=1000;
T_ref=25;

%% Fixed
k=1.380650e-23;
q=1.602176e-19 ;

%%
% Note that Ns_=Ns*Nc_m_s,but Ns=1 thus Ns_=1*Nc_m_s=Nc_m_s
% In the same way, Np_=Nc_m_p

detla=T-T_ref;
Vt=k*(T+273.15)/q;
a=n*Vt;
Rsh=Rshn*Gn/G;
Io=(Isc_n+Ki*detla+((Isc_n+Ki*detla)*Rs-(Nc_m_p/Nc_m_s)*(Voc_n+Kv*detla))/Rsh)/(Nc_m_p*(exp((Voc_n+Kv*detla)/(a*Nc_m_s))-exp((Isc_n+Ki*detla)*Rs/(a*Nc_m_p))));
Ipv=(Ipvn+Ki*detla)*G/Gn;

%% Iterations
vf=Voc_n;
pp=vf*20; % Number of searching steps
I = [];
V = [];
P = [];
Pmax=0;
for i=0:pp
    V (i+1)=i*vf/pp;
    VV=i*vf/pp;
    C=Rs/(a*Nc_m_p);
    D=VV/(a*Nc_m_s);
    A=((Rsh+Rs)/Rsh)*(1/(-Nc_m_p*Io));
    B=(-Nc_m_p*Ipv-Nc_m_p*Io+(VV*Nc_m_p/(Nc_m_s*Rsh)))*(1/(-Nc_m_p*Io));
    X=(-C/A)*(exp((D-(C*B/A))));
    II=-(1/C)*lambertw(X)-B/A;
 
% if (I(i+1)<=0)
%   I(i+1)=0
%   break
% end
%     I(i+1)=II;
    P(i+1)=II*VV;
    if P(i+1)> Pmax
        Pmax=P(i+1);
        Vmax=VV;
    end

end

end
